apiVersion: apps/v1
kind: Deployment
metadata:
  name: friend-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: friend
  template:
    metadata:
      labels:
        app: friend
    spec:
      containers:
        - name: friend
          image: padugyamfi/friend
          env:
            - name: POSTGRES_HOST
              value: host.docker.internal
            - name: POSTGRES_USER
              value: pauladu
            - name: POSTGRES_PASSWORD
              value: password
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: server
---
apiVersion: v1
kind: Service
metadata:
  name: friend-srv
spec:
  selector:
    app: friend
  ports:
    - name: friend
      protocol: TCP
      port: 3000
      targetPort: 3000
