apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
    - host: paperclass.com
      http:
        paths:
          - path: /programs/?(.*)
            backend:
              serviceName: extract-srv
              servicePort: 3000
          - path: /?(.*)
            backend:
              serviceName: oauth-srv
              servicePort: 3000