apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
    - host: paperclass.com
      http:
        paths:
          - path: /f/status/?(.*)
            backend:
              serviceName: friend-srv
              servicePort: 3000
          - path: /g/post/?(.*)
            backend:
              serviceName: timeline-srv
              servicePort: 3000
          - path: /c/post/?(.*)
            backend:
              serviceName: post-ingestion-srv
              servicePort: 3000
          - path: /?(.*)
            backend:
              serviceName: user-srv
              servicePort: 3000