apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth
  template:
    metadata:
      labels:
        app: oauth
    spec:
      containers:
        - name: oauth
          image: padugyamfi/oauth
          env:
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: keys
                  key: PORT
            - name: MONGO_OAUTH_URI
              valueFrom:
                secretKeyRef:
                  name: keys
                  key: MONGO_OAUTH_URI
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: keys
                  key: GOOGLE_CLIENT_ID
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: keys
                  key: CLIENT_SECRET
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: keys
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: oauth-srv
spec:
  selector:
    app: oauth
  ports:
    - name: oauth
      protocol: TCP
      port: 3000
      targetPort: 3000
