apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-processor-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-processor
  template:
    metadata:
      labels:
        app: post-processor
    spec:
      containers:
        - name: post-processor
          image: padugyamfi/post-processor
          env:
            - name: REDIS_HOST
              value: post-processor-redis-srv
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: server
