apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: padugyamfi/user
          env:
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: user-keys
                  key: PORT
            - name: MONGO_USER_URI
              valueFrom:
                secretKeyRef:
                  name: user-keys
                  key: MONGO_USER_URI
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: user-keys
                  key: GOOGLE_CLIENT_ID
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: user-keys
                  key: CLIENT_SECRET
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: user-keys
                  key: JWT_KEY
            - name: REDIS_HOST
              value: user-redis-srv
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: server
---
apiVersion: v1
kind: Service
metadata:
  name: user-srv
spec:
  selector:
    app: user
  ports:
    - name: user
      protocol: TCP
      port: 3000
      targetPort: 3000
